### ISSUE TITLE
[$ 200] Voyager integration

### ISSUE THREAD

**Issue by luceos** [tenancy/docs#67]
There's an increasing demand for decent tutorials explaining how to integrate the [Laravel Voyager](https://laravelvoyager.com/) admin dashboard with [hyn/multi-tenant](https://laravel-tenancy.com/docs/hyn/5.3). Such a tutorial would require at least:

- how to set up the default laravel app
- install both packages
- explain how to use tenant/system behavior with voyager in depth
- provide demo repository

Make sure you open a WIP PR as soon as possible (subject of PR needs to start with WIP), indicating your interest in closing this issue and taking a shot at the $ 200 reward. The reward will be given to the best tutorial at the end of this month or thereafter and only with the approval of at least two staff members. 

The full tutorial has to be a PR against the docs, not just the link ;) This way we can update it for newer versions too without having to coerce the original author into oblivion..

Also:

- you can add the link the new page [here](https://github.com/tenancy/docs/blob/03b353fcbe85e2d11e7083c04ff673a403ed79ed/docs.yaml#L108)
- and feel free to attach your meta information in the YAML frontmatter like [so](https://raw.githubusercontent.com/tenancy/docs/master/docs/hyn/5.1/full-featured-tutorial.md), I'll make sure we'll link the author again the docs, nevertheless your contribution is under [our contributor guidelines](https://github.com/hyn/multi-tenant/blob/5.x/.github/CONTRIBUTING.md#contributor-license-agreement)

**Comment by m1guelpf** [comment]
Wanna try this, I'll open a PR with a draft URL, but keep in mind the final URL will be different :)

**Comment by gruz** [comment]
@luceos 
Hi.
Here is my tutorial on tenancy-voyager integration. 
Please have a look and tell what can be improved.
https://github.com/gruz/multi-tenancy-voyager-tries

**Comment by luceos** [comment]
@fletch3555 could you take a peak?

**Comment by gruz** [comment]
@luceos @fletch3555 
Please check my tutorial. I'd create a pull request, but I don't want to change it twice (I assume there will be some changes) in my repo and in the pull request upon your comments.

If it's a matter of the money, I don't insist on any payment. Just don't want someone else to take results of my job and win the prize. :-)

**Comment by gruz** [comment]
@luceos 

My approach works by copy-pasting. And bash script comments describe (or may be improved to better describe) what which part is intended to do. If I break it into smaller pieces of text and code snipes one would need to copy-paste a dozen of code snippets instead of one bash script. 

I'd suggest to improve bash script comments to give better understanding on what is going on and why. But not to remove bash scripting.

I tried to comment the bash script to tell both manual way and script way. I'm frustrated to hear *you should explain what is needed and why in a tutorial* like it's never described.

E.g. 

```bash
# Disable autodiscover for Voyager to load it only after your AppServiceProvider is loaded.
# This is needed, because you must be sure Voyager loads all it's staff after the
# DB connection is switched to tenant

# Alas composer CLI way to update composer.json fails here (is not able to write as waay)
# `composer config extra.laravel.dont-discover tcg/voyager`
# So we need to update composer.json on our own.

# Manual
# In composer.json add `tcg/voyager` to `dont-disover` array:
# "extra": {
#     "laravel": {
#         "dont-discover": [
#             "tcg/voyager"
#         ]
#     }
# },

# Bash script
sed -i "s/\"dont\-discover\"\: \[\]/\"dont\-discover\"\: [\"tcg\/voyager\"]/g" composer.json
```

Supporting to variants of document with bash/comments and with splitted code snippets is hard and error causing. And removing the working bash script doesn't seem to be logical.

With docker approach it's easy to start a working project quickly. One is free not to use a docker and it's explained how to do it without a docker. I don't see any reason to remove the working  and optional docker part as well.

> Everything related to docker and non-docker should probably be reduced to simpler versions.

What can be simplified for a non-docker part in the places of "docker way - non-docker way"?

> These files should probably be documented in the tutorial and suggested where they need to be placed.

The bash script shows where to place which file like this. 

```
cat << 'EOF' > app/DatabasePasswordGenerator.php
<?php 

namespace App;

use Hyn\Tenancy\Generators\Database\DefaultPasswordGenerator;
use Hyn\Tenancy\Contracts\Website;
use Illuminate\Contracts\Foundation\Application;
...

EOF
```

So there is the path where to place the file and the file contents. Maybe I can comment more on the purpose of each file. 

And it's explain how to undertsnand ```cat << 'EOF' > app/DatabasePasswordGenerator.php```

---
So my suggestion is to better comment the bash script for users which want to read and understand what and why. But not to remove the docker part or the bash scripting part as you request.

Or I can rewrite my documentation as an article without bash/docker, but it will not be tied to my repo and this will be hard to support on changes and improvements.

And I don't undestand then how I *provide demo repository*. Would my current repo with my current documentation be ok?

---

I did huge investigation and spent dozens of hours. I think I did 90% of job except some text rephrase you demand. Your 50$ sounds like you did only 25% of the task. 

I do this not because of the money, 200$ is valuable but not critical for me. But I don't want someone who rephrases test to get them. Just don't want to feel myself a fool :-)

**Comment by luceos** [comment]
I totally understand that a lot of time went into this. But in its current state is not usable to us. Keeping the tutorial as clear as possible - without any helper scripts etc - and references of/to docker would be necessary for it to get adopted into the docs.

When writing an article for someone elses' website, it's always useful to try to match their writing.

- Nowhere in the current docs do we point at the hosting environment, this is on purpose. We don't want to increase the support load about that subject. 
- Keeping documentation as simple and clear as possible, without introducing commands that behave differently across OS'es like [sed](https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed) is just another example.

**Comment by gruz** [comment]
> Keeping documentation as simple and clear as possible, without introducing commands that behave differently across OS'es like sed is just another example.

I say "either do it manually this replacement or here is a shortcut to do it automatically". So I try to simplify user their life.

Ok. I'll post an article here in a while without sed which you don't like so much (-:

> how to set up the default laravel app

But what should I then do with DB setup? 
I can say `composer create-project --prefer-dist laravel/laravel` but I can say nothing about DB setup except "somehow setup DB and execute the commands from HYN docs". Would it be ok to meet `how to set up the default laravel app` ?

> provide demo repository

Would my current repo be ok?

**Comment by luceos** [comment]
I think we can agree that the repo is a great resource for getting the package integrated into voyager. I'm okay with paying you for the effort, but I just don't feel comfortable enough to use it inside the docs, it might become too outdated too soon and it might raise more questions we would need to answer for. Are you okay with that?

**Comment by gruz** [comment]
@luceos I've reworked my integration guide without docker, without any bash scripting. Added more text descriptions on each step. Can you please check and tell what is not ok for now?
